# .github/workflows/deploy.yml
name: Build and Deploy to S3, Clear CloudFront Cache
on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Choose an Ubuntu runner
    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: vishal-9878/CICD-Work

      # Step 2: Install dependencies
      - name: Install Node.js and Dependencies
        uses: vishal-9878/CICD-Work
        with:
          node-version: '16'  # Adjust to the Node.js version you're using
      - run: npm install  # Install project dependencies
      - run: npx create-react-app react-app
      
      # Step 3: Build the React.js app
      - name: Build React App
        run: cd react-app && npm run build  # Build the React app
      
      # Step 4: Sync build folder to S3
      - name: Upload to S3
        uses: s3-sync-action@v0.5.1  # Sync S3 with a GitHub Action
        with:
          args: 'build/ s3://work-bucket-vishal/'  # Adjust to your S3 bucket name
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID from GitHub Secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key from GitHub Secrets
          AWS_REGION: 'us-east-1'  # The AWS region where your S3 bucket is located

      # Step 5: Clear CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id your-cloudfront-id --paths "/*"  # CloudFront cache invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
