name: Build and Deploy to S3, Clear CloudFront Cache
on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Updated to use Node.js 20

      #- run: npm i  # Install project dependencies
      - run: npx create-react-app react-app  # Optionally, remove this step if you already have a React app

      - name: Build React App
      # Step 3: Build the React.js app
        run: cd react-app && npm run build  # Build the React app


      # Step 4: Configure AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3  # Set AWS credentials
        with:
          AWS_ACCESS_KEY_ID: AKIA5JDSKOY3LV7H5RVU
          AWS_SECRET_ACCESS_KEY: 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
          aws-region: 'us-east-1' 

      # Step 5: Sync build folder to S3
      - name: Upload to S3
        run: |
          aws s3 sync react-app/build/ s3://work-bucket-vishal/ --delete 
        env:
          AWS_ACCESS_KEY_ID: AKIA5JDSKOY3LV7H5RVU
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: 'us-east-1'

      # Step 6: Clear CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id your-cloudfront-id --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: AKIA5JDSKOY3LV7H5RVU
          AWS_SECRET_ACCESS_KEY: JjagzMkI//LnYdpgoGxzPshnqRDs3eirfEac3Fr3
          AWS_REGION: 'us-east-1'
