name: Install AWS CLI and Run Commands

on:
  push:
    branches:
      - main  # Modify as needed

jobs:
  install_aws_cli:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures you have your repository's content

      # Step 2: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli  # Install AWS CLI

      # Step 3: Configure AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3  # Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Adjust to your AWS region

      # Step 4: Verify AWS CLI Installation
      - name: Verify AWS CLI Installation
        run: aws --version  # Check AWS CLI version

      # Step 5: List S3 Buckets (for verification)
      - name: List S3 Buckets
        run: aws s3 ls  # List S3 buckets to ensure AWS CLI is working
