name: Build and Deploy to S3, Clear CloudFront Cache
on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the workflow on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Choose an Ubuntu runner
    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to the Node.js version you're using
      - run: npm install  # Install project dependencies
      - run: npx create-react-app react-app

      # Step 3: Build the React.js app
      - name: Build React App
        run: cd react-app && npm run build  # Build the React app

      # Step 4: Sync build folder to S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0  # Correctly reference the S3 sync action
        with:
          args: 'react-app/build/ s3://work-bucket-vishal/ --delete'  # Adjusted the path and added the --delete option
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # Adjust to your region

      # Step 5: Clear CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id your-cloudfront-id --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
